server:
  port: 8082

auth-server:
  base-url: http://localhost:9000/authorization-api
  public-url: ${auth-server.base-url}

oauth2:
  client:
    client-id: react-note
    client-secret: react-note-secret

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${auth-server.base-url}/oauth2/jwks
